[project]
name = "sound-soul"
version = "0.1.0"
authors = [{ name = "project-DnCo", email = "project.dnco@gmail.com" }]
description = "Soul Eater themed discord bot."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "discord-py[voice]>=2.6.4",
    "pydantic>=2.12.4",
    "pydantic-settings>=2.12.0",
]


[project.scripts]
bot = "sound_soul:main"


[tool.uv]
cache-dir = "./.uv_cache"


[build-system]
requires = ["uv_build >= 0.9.5, <0.10.0"]
build-backend = "uv_build"
